name: Image Vulnerabilities Scan

on:
  schedule:
    - cron: "0 12 * * 1"

permissions:
  contents: read

jobs:
  scan:
    name: Check image vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Build Docker image
        env:
          IMG: "msi-acrpull:${{ github.sha }}"
        run: make docker-build

      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@7088d18dcb87884bc7b5a4000d5517d758e9aa13 # master
        with:
          image-ref: "msi-acrpull:${{ github.sha }}"
          format: "table"
